# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'App-LogInFirebase-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App-LogInFirebase-Demo

  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SVProgressHUD'
  pod 'Firebase/Core'


  target 'App-LogInFirebase-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'App-LogInFirebase-DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
