# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FBLogInTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for de-boca-en-boca
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Crash'
  
  
  #Pod Google Sign In
  pod 'GoogleSignIn'
  
  pod 'FacebookSDK'
 

  # Pods for FBLogInTest

  target 'FBLogInTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FBLogInTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
