# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alamofire1st' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alamofire1st

  target 'Alamofire1stTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Alamofire1stUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'Alamofire'

end
